# Generated by Django 3.2.15 on 2022-09-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_pacientes_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='foto',
            field=models.ImageField(upload_to='fotos/%Y/%m'),
        ),
    ]
