# Generated by Django 3.2.15 on 2022-09-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_alter_pacientes_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='telefone',
            field=models.IntegerField(max_length=19),
        ),
    ]
