# Generated by Django 3.2.15 on 2022-09-12 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_alter_pacientes_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='DadosPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('gordura', models.IntegerField()),
                ('musculo', models.IntegerField()),
                ('hdl', models.FloatField()),
                ('ldl', models.FloatField()),
                ('colesterol_total', models.FloatField()),
                ('trigliceridios', models.FloatField()),
                ('nutri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.pacientes')),
            ],
        ),
    ]
