# Generated by Django 3.2.15 on 2022-09-13 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_rename_nutri_dadospaciente_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospaciente',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
